name: CI

on:
  push:
    branches:
      - dev       # Run tests on dev push
      - main      # Run tests on main push
  pull_request:
    branches:
      - main      # Run tests automatically when PR targets main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Make Maven wrapper executable
        run: chmod +x mvnw
      - name: Run tests
        run: ./mvnw -B test